### ISSUE TITLE
Task createXCFramework fails when module contains a dash "-"

### ISSUE THREAD

**Issue by kalinjul** [luca992/multiplatform-swiftpackage#12]
I have a module named "oidc-core".
The task createUniversalIosSimulatorFramework generates 
`build/bin/iosSimulatorUniversal/releaseFramework/oidc_core.framework`
The task createXCFramework tries to pick the framework up in 
`build/bin/iosSimulatorUniversal/releaseFramework/oidc-core.framework` ... where it cannot find it:

```
> Task :oidc-core:createXCFramework FAILED
error: the path does not point to a valid framework: /Users/julian/Workspace/repos/kotlin-multiplatform-oidc/oidc-core/build/bin/iosSimulatorUniversal/releaseFramework/oidc-core.framework
```

The dash ```-``` gets replaced (by kotlin multiplatform?) with an underscore, but this replacement gets undone in CreateXCFrameworkTask:

https://github.com/luca992/multiplatform-swiftpackage/blob/5aa43d83984f225fc0452ce6f0479811ae06cc56/src/main/kotlin/com/chromaticnoise/multiplatformswiftpackage/task/CreateXCFrameworkTask.kt#L107-L120
I guess ```${frameworkName.value}.``` is not correct when the name contains a dash (and maybe other special characters, too)

Workaround in build.gradle.kts:

```
kotlin {
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach {
        it.binaries.framework {
            baseName = "basenameWithoutDash"
        }
    }
}
```

**Comment by luca992** [comment]
So just replacing `-` with `_` in `frameworkName` should work right?

**Comment by kalinjul** [comment]
I guess - but I'm not sure about other characters that get replaced and have to be respected.
Maybe the last part of the file path could be used instead?

**Comment by luca992** [comment]
@kalinjul considering the string is from a module/folder name, I don't think any other special characters are allowed by operating systems?

Or at least dashes are the only ones that get converted automatically I think.

**Comment by luca992** [comment]
try `2.2.1` 👍
