### ISSUE TITLE
 The dSYMs are missing when the task is launched for the first time after cleaning the build directory

### ISSUE THREAD

**Issue by lukisk** [luca992/multiplatform-swiftpackage#15]
./gradew clean
./gradlew createXCFramework //missing dsyms
./gradlew createXCFramework //dsyms ok

I tested it for release and arm64 architecture.

The problem is in this condition:
https://github.com/luca992/multiplatform-swiftpackage/blob/cb13b931835dcb8e05546a17ff056a2337ba2cc4/src/main/kotlin/com/chromaticnoise/multiplatformswiftpackage/task/CreateXCFrameworkTask.kt#L188

**Comment by luca992** [comment]
Ohh thanks for finding what was causing that! I haven't had time to dig into why I've had to run it twice.

**Comment by lukisk** [comment]
I think that at the time when the task is being created, there is still an empty build directory, so the condition is false. Perhaps the command for creating the framework could be moved to the 'doLast' block.

**Comment by luca992** [comment]
@lukisk try 2.2.2-SNAPSHOT 

Lmk if how it goes.

use this repo:

```
repositories {
    maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
}
```

**Comment by luca992** [comment]
I tried moving that part into doLast

https://github.com/luca992/multiplatform-swiftpackage/commit/d5273276d7d5bf873927677c295195787211ed45

**Comment by lukisk** [comment]
@luca992 
Build ends with this error:
```
> Task :multiplatform:createXCFramework
Command line invocation:
    /Applications/Xcode-15.0.1.app/Contents/Developer/usr/bin/xcodebuild

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2024-01-03 16:17:36.355 xcodebuild[69274:14308976] Writing error result bundle to /var/folders/8k/7dd9jgn11z73smwj81b6nnlh0000gn/T/ResultBundle_2024-03-01_16-17-0036.xcresult
xcodebuild: error: The directory /Users/..../multiplatform does not contain an Xcode project.
```

**Comment by luca992** [comment]
@lukisk alright I'll take a deeper look soon when I put out a release of one of my libraries using this, unless you want to dig into it more

**Comment by lukisk** [comment]
@luca992 i fixed it

**Comment by luca992** [comment]
@lukisk Thanks for that! `2.2.2-SNAPSHOT` has been updated with your fix. I'll release 2.2.2 after I try it out myself soon

**Comment by idevdroidapps** [comment]
just wondering if 2.2.2 is ready

**Comment by luca992** [comment]
@idevdroidapps It probably is. I just haven't tried it to make sure yet. I'll get to it in the next couple days. If the snapshot is working well for you lmk

**Comment by luca992** [comment]
@idevdroidapps [released](https://github.com/luca992/multiplatform-swiftpackage/releases) seems to be working well, thanks again @lukisk
