### ISSUE TITLE
Resolving dependency configuration 'metadataCompilationApi' is not allowed as it is defined as 'canBeResolved=false'.

### ISSUE THREAD

**Issue by jagtejsodhi** [luca992/multiplatform-swiftpackage#17]
Thanks for the fork! Running into some issues when integrating:

Here's my setup:

```
plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    id("io.github.luca992.multiplatform-swiftpackage") version "2.2.1"
}

...

multiplatformSwiftPackage {
    swiftToolsVersion("5.3")

    targetPlatforms {
        iOS { v("16") }
    }

    outputDirectory(File(projectDir, "swiftpackage"))

    distributionMode { local() }

    buildConfiguration { debug() }
}
```

However, when running `./gradlew createSwiftPackage`, I see this error:

```
* What went wrong:
Configuration cache state could not be cached: field `apiConfiguration` of `org.jetbrains.kotlin.gradle.plugin.mpp.compilationImpl.DefaultKotlinCompilationConfigurationsContainer` bean found in field `dependencyConfigurations` of `org.jetbrains.kotlin.gradle.plugin.mpp.compilationImpl.KotlinCompilationImpl$Params` bean found in field `params` of `org.jetbrains.kotlin.gradle.plugin.mpp.compilationImpl.KotlinCompilationImpl` bean found in field 
...
:shared:createUniversalIosSimulatorFramework` of type `org.jetbrains.kotlin.gradle.tasks.FatFrameworkTask`: error writing value of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration'
> Resolving dependency configuration 'metadataCompilationApi' is not allowed as it is defined as 'canBeResolved=false'.
  Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'metadataCompilationApi' should be resolved.
```

I think that error might just be some issue w/ configuration cache. Further, if I run `./gradlew createSwiftPackage --no-configuration-cache`, then I get this error:

```
> Task :xcodeVersion FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xcodeVersion'.
> org.jetbrains.kotlin.konan.MissingXcodeException: An error occurred during an xcrun execution. Make sure that Xcode and its command line tools are properly installed.
  Failed command: /usr/bin/xcrun xcodebuild -version
  Try running this command in Terminal and fix the errors by making Xcode (and its command line tools) configuration correct.
```

Thanks in advance.

**Comment by luca992** [comment]
It's telling you `Make sure that Xcode and its command line tools are properly installed.` Did you do that? Make sure command line tools are installed correctly

**Comment by jagtejsodhi** [comment]
Xcode and command line tools are definitely both installed (as I actively develop iOS apps). 

The gradle task is attempting to invoke xcrun from  `/usr/bin/xcrun`, but the xcrun path on my M1 is:

```
xcrun --show-sdk-path                   
                     
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```

which I believe is correct for M1, but please correct me if I'm wrong. 
TIA

**Comment by luca992** [comment]
I don't think this is a library issue.

Try some of the solutions here to try and fix your command line tools:
 https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

**Comment by jagtejsodhi** [comment]
Interestingly enough, there was a Mac software update which included an update to Command Line tools. After completing the update, everything works as expected. Not sure what was wrong before, but thanks for the guidance.

**Comment by luca992** [comment]
yeah usually you need to launch xcode after an update to accept some terms, or something along those lines if I remember correctly. Happy you got it figured out 👍
