### ISSUE TITLE
Support for Gradle configuration cache

### ISSUE THREAD

**Issue by shpasha** [luca992/multiplatform-swiftpackage#5]
Kotlin 1.9.0-RC comes with support for [Gradle configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) in multiplatform libraries.

https://kotlinlang.org/docs/whatsnew-eap.html#preview-of-gradle-configuration-cache-in-kotlin-multiplatform

It would be great to add gradle configuration cache support in this plugin

**Comment by luca992** [comment]
Sorry, I don't why I'm not getting notifications for these issues. If you make a pr I'll review it and publish it.

**Comment by luca992** [comment]
@shpasha try `2.2.0-SNAPSHOT` Lmk if how it goes and I can merge it afterwards if all is well.

use this repo:
```
repositories {
    maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
}
```

**Comment by aegis123** [comment]
Any progress on this? since 2.2.2 is released?

**Comment by luca992** [comment]
If you want to confirm that snapshot works as expected I'll release an update with it. @aegis123

**Comment by luca992** [comment]
I added to `2.2.3` let me know if there are problems
