### ISSUE TITLE
Incorrect properties file in META-INF

### ISSUE THREAD

**Issue by stefan-schweizer** [luca992/multiplatform-swiftpackage#6]
When adding the plugin as a dependency in buildSrc (it is applied in a convention plugin), the build fails with the following error:

```
> Task :buildSrc:generateExternalPluginSpecBuilders FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:generateExternalPluginSpecBuilders'.
> implementationClass must not be null
```

It can be reproduced with a setup similar to this:
```
plugins {
    `kotlin-dsl`
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("io.github.luca992.multiplatform-swiftpackage:io.github.luca992.multiplatform-swiftpackage.gradle.plugin:2.1.2")
}
```

I am pretty sure the reason for this error is, that there is an incorrect properties file in META-INF coming directly from the [source](https://github.com/luca992/multiplatform-swiftpackage/blob/master/src/main/resources/META-INF/gradle-plugins/com.chromaticnoise.multiplatform-swiftpackage.properties) with an incorrect spelling of `implementationClass` (should be `implementation-class`). As the implementation class is also set in `build.gradle` and META-INF contains a second correct properties file in the resulting jar, the incorrect file most likely can be deleted.

**Comment by luca992** [comment]
Sorry, I don't why I'm not getting notifications for these issues. Can you make a pr?

**Comment by luca992** [comment]
Thanks! I'm publishing `2.1.3-SNAPSHOT` now, can you try it and lmk if it fixes your issue. I'll publish a normal version after that if so.

use this repo:

```
repositories {
    maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
}
```

**Comment by stefan-schweizer** [comment]
@luca992, thanks! I've tested the snapshot and the problem with the `implementationClass must not be null` is fixed now. Though I am using a different setup without a convention plugin now that also still works with the change.

**Comment by luca992** [comment]
@stefan-schweizer Cool. Also, just wondering before I merge it, I honestly have no idea what that file does. Why delete it rather that fix the name?

**Comment by stefan-schweizer** [comment]
@luca992, the file tells Gradle where to find the actual plugin implementation: https://docs.gradle.org/current/userguide/custom_plugins.html#behind_the_scenes

If you look into the jar-file's _META-INF/gradle-plugins_ folder, there is a correct properties file that is generated from [this](https://github.com/luca992/multiplatform-swiftpackage/blob/master/build.gradle.kts#L64) part in build.gradle. Before there were two properties files, the incorrect one that I just deleted and the correct one that is generated.

**Comment by luca992** [comment]
Ahh that's right, you did say that. Got it 👍
