### ISSUE TITLE
unknown options: -ios_simulator_version_min -sdk_version 

### ISSUE THREAD

**Issue by tristangrichard** [luca992/multiplatform-swiftpackage#9]
`./gradlew createSwiftPackage` fails with
e: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors
ld: unknown options: -ios_simulator_version_min -sdk_version 

since macOS 14

**Comment by tristangrichard** [comment]
Updating dependencies to the latest helped

**Comment by georkost4** [comment]
@tristangrichard do you mind sharing what kind of dependencies you updated?

**Comment by tristangrichard** [comment]
I don't recall exactly what did the trick but from I can in the commit that I bumped to following versions:
```
kotlin("multiplatform").version("1.9.10").apply(false)
kotlin("plugin.serialization") version "1.9.10"
id("io.github.luca992.multiplatform-swiftpackage") version "2.1.4"
jvmTarget = "17"
```
